### ISSUE TITLE
Problème d'énoncé

### ISSUE THREAD

**Issue by sdam69** [andfanilo/pyspark-tutorial#4]
Bonjour, 
Le td "2-Advanced-SQL-and-ML" à une erreur dans l'énoncé. 
Question : Through some regex, the regex_extract UDF and SQLTransformer, get the title of a person from the Name column in a Title column. Drop the Name column afterwards.
La nouvelle doit être nommée Title, mais la vérification se fait sur la colonne "Civility".

Bonne journée 

Cdlt

**Comment by andfanilo** [comment]
Merci pour l'info, finally fixed it!
